version: '3'

services:
  timeregistrationdemo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  quickstartidentityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat
