version: '3'

services:
  demodb:
    image: microsoft/mssql-server-windows-express
    environment:
      sa_password: azurePASSWORD123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
  timeregistrationdemo:
    image: timeregistrationdemo.webapi
    build:
      context: ./TimeRegistrationDemo.WebApi
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  quickstartidentityserver:
    image: quickstartidentityserver
    build:
      context: ../Authentication/src/QuickstartIdentityServer
      dockerfile: Dockerfile
    ports:
      - "5000:80"